CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descripcion text NOT NULL CHECK (descripcion <> ''),
    stock INTEGER NOT NULL,
    price decimal(12,2)
);

INSERT INTO products(descripcion,stock,price) VALUES ('Arroz Gallito de Oro',15,5.50);